.build-site:
  image: jackfirth/racket:7.4-cs-full
  variables:
    RACKET_VERSION: "7.4"
    RACKET_DIR: $CI_PROJECT_DIR/install
    RACKET_MINIMAL: 1
  before_script:
    - raco pkg install --auto --no-setup frog rosette
    - raco setup -D frog rosette
  script:
    - make site

pages:
  extends: .build-site
  stage: deploy
  artifacts:
    paths:
    - public
  only:
    - master

  
