.build-site:
  image: jackfirth/racket:7.4-full
  variables:
  before_script:
    - raco pkg install --auto --no-setup frog rosette
    - raco setup -D frog rosette
  script:
    - make site

pages:
  extends: .build-site
  stage: deploy
  artifacts:
    paths:
    - public
  only:
    - master

  
