image: debian:stable-slim

build-site:
  variables:
    RACKET_VERSION: "7.3"
    RACKET_DIR: $CI_PROJECT_DIR/install
  before_script:
    - apt-get update && apt-get install -y make git curl python-pygments 
    - if [ ! -d $RACKET_DIR ]; then git clone https://github.com/greghendershott/travis-racket.git && cat travis-racket/install-racket.sh | bash;  fi
    - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us
    - raco pkg install --auto --no-setup frog rosette
  script:
    - make site
  cache:
    key: racket-73
    paths:
      - $RACKET_DIR
  
pages:
  extends: build-site
  stage: deploy
  artifacts:
    paths:
    - public
  only:
    - master

  
