image: debian:stable-slim

stages:
  - deploy
  - remember

.build-site:
  variables:
    RACKET_VERSION: "7.3"
    RACKET_DIR: $CI_PROJECT_DIR/install
    RACKET_MINIMAL: 1
  before_script:
    - apt-get update && apt-get install -y make git curl python-pygments 
    - if [ ! -d $RACKET_DIR ]; then git clone https://github.com/greghendershott/travis-racket.git && cat travis-racket/install-racket.sh | bash;  fi
    - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us
    - raco pkg install --auto --no-setup frog rosette
    - raco setup -D frog
  script:
    - make site
  cache:
    key: racket-73
    paths:
      - $RACKET_DIR
  
pages:
  extends: .build-site
  stage: deploy
  artifacts:
    paths:
    - public
  only:
    - master

rememberme:
  image: alpine:latest
  stage: remember

  needs:
    - job: pages
      artifacts: true
      
  before_script:
    - apk add curl
  scripts:
    - ./rememberme.sh
  
