name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    container: debian:stable-slim

    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update
          apt-get install -y openssl
      - uses: Bogdanp/setup-racket@v0.9
        with:
          architecture: 'x64'      # (x64 or x86), ignored on Linux
          distribution: 'minimal'  # or 'minimal'
          variant: 'CS'            # or 'CS' for Racket-on-Chez
          version: '7.7'           # or 'current' for the latest snapshot
          packages: 'darwin, rosette'
      - run: make site
      - run: ./rememberme.sh
          
